/****************************************************************
 * file gccjit-refpersys/main.c
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Description:
 *      This file is part of the Reflective Persistent System.
 *      It is almost its main program.
 *
 * Author(s):
 *      Basile Starynkevitch, France   <basile@starynkevitch.net>
 *      Abhishek Chakravarti, India    <abhishek@taranjali.org>
 *      Nimesh Neema, India            <nimeshneema@gmail.com>
 *
 *      © Copyright 2019 - 2024 The Reflective Persistent System Team
 *      team@refpersys.org & http://refpersys.org/
 *
 * You can consider RefPerSys as either GPLv3+ or LGPLv3+ licensed (at
 * your choice)
 *
 * License: GPLv3+ (file COPYING-GPLv3)
 *    This software is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details or the Lesser
 *    General Public License.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ***/

//// TODO: avoid any non-generated header file!

#define _GNU_SOURCE
#include <stdlib.h>
#include <stdio.h>
#include <stdatomic.h>
#include <unistd.h>
#include <time.h>
#include <sys/time.h>
#include <sys/random.h>
#include <getopt.h>
#include <string.h>
#include <errno.h>
#include <assert.h>
#include <zlib.h>
#include <unistr.h>
#include <pthread.h>
#include <threads.h>
#include <backtrace.h>
#include <readline/readline.h>
#include <libgccjit.h>

gcc_jit_context *jitctx_RPS;
const char *progname_RPS;
const char *zlibv_RPS;
struct backtrace_state *backtrace_state_RPS;
thread_local struct random_data random_data_RPS;
thread_local volatile atomic_flag random_inited_RPS;

char full_source_main_RPS[384];

#ifndef SHORTGITID
#error compilation command without SHORTGITID
#endif

const char shortgitid_RPS[] = SHORTGITID;


#ifndef SOURCEDIR
#error compilation command without SOURCEDIR
#endif

const char sourcedir_RPS[] = SOURCEDIR;

#define FATAL_AT_BIS(Fil,Lin,Func,Fmt,...) do {         \
    char thrname##Lin[32];                              \
    memset(thrname##Lin, 0, sizeof(thrname##Lin));      \
    pthread_getname_np(pthread_self(), thrname##Lin,    \
                       sizeof(thrname##Lin));           \
    fprintf (stderr, "%s:%d:%s [%s]", (Fil), (Lin),     \
             (Func), thrname##Lin);                     \
    fprintf (stderr, Fmt "\n", ##__VA_ARGS__);          \
    fprintf (stderr, "%s: shortgit %s\n",               \
             progname_RPS, shortgitid_RPS);             \
    fflush (stderr);                                    \
    if (backtrace_state_RPS)                            \
      backtrace_print (backtrace_state_RPS, 1, stderr); \
    fflush(NULL);                                       \
    abort(); } while(0)

#define FATAL_AT(Fil,Lin,Func,Fmt,...) \
  FATAL_AT_BIS(Fil,Lin,Func,Fmt,##__VA_ARGS__)

#define FATAL(Fmt,...) FATAL_AT(__FILE__,__LINE__,__FUNCTION__,Fmt,##__VA_ARGS__)


void
backtrace_error_RPS (void *data, const char *msg, int errnum)
{
  if (data)
    {
    }
  fprintf (stderr, "backtrace_error_RPS: %s (%d:%s)\n", msg, errnum,
           strerror (errnum));
  fflush (NULL);
}                               /* end backtrace_error_RPS */


void
emit_gplv3_notice_AT_RPS (FILE *fout, const char *fil, int lin,
                          const char *fromfun, const char *path,
                          const char *linprefix, const char *linsuffix,
                          char *explain)
{
  assert (fout);
  assert (path);
#define EMIT_PRINTF(Fmt,...) do {               \
    if (linprefix)                              \
      fputs(linprefix,fout);                    \
  fprintf(fout,Fmt,##__VA_ARGS__);              \
  if (linsuffix)                                \
    fputs(linsuffix,fout);                      \
  fputc('\n', fout);                            \
} while(0)
  time_t nowtime = time (NULL);
  struct tm nowtm = { };
  localtime_r (&nowtime, &nowtm);
  EMIT_PRINTF ("SPDX-License-Identifier: GPL-3.0-or-later");
  EMIT_PRINTF ("GENERATED [GPLv3+] file %s / DO NOT EDIT", path);
  if (explain)
    EMIT_PRINTF ("! %s !", explain);
  EMIT_PRINTF ("! generating git %s !", shortgitid_RPS);
  EMIT_PRINTF ("This %s file is generated by %s from %s:%d:%s",
               path, progname_RPS, fil, lin, fromfun);
  EMIT_PRINTF ("© Copyright 2023 - %d - RefPerSys team",
               (nowtm.tm_year + 1900));
  EMIT_PRINTF ("License: GPLv3+ (file COPYING-GPLv3)");
  EMIT_PRINTF ("see refpersys.org & github.com/RefPerSys/gccjit-refpersys");
  EMIT_PRINTF ("Contact team@refpersys.org and/or ...");
  EMIT_PRINTF ("Basile STARYNKEVITCH <basile@starynkevitch.net> (France)");
#undef EMIT_PRINTF
}                               /* end emit_gplv3_copyright_notice_AT_RPS */

#define EMIT_GPLV3_COPYRIGHT_RPS(Fout,Path,Lpref,Lsuff,Explain) \
  emit_gplv3_notice_AT_RPS(Fout,                                \
                           __FILE__,__LINE__,__FUNCTION__,      \
                           (LPref),(Lsuff),(Explain))

int32_t
randomi32_RPS (void)
{
  if (__builtin_expect (!atomic_flag_test_and_set (&random_inited_RPS), true))
    {
      static thread_local char randbuf[64];
      memset (&random_data_RPS, 0, sizeof (random_data_RPS));
      if (getrandom (&randbuf, sizeof (randbuf), 0) <
          (long) sizeof (randbuf) / 2)
        FATAL ("failed to initialize random (%s)", strerror (errno));
      unsigned seed = (unsigned) (time (NULL) + getpid ());
      initstate_r (seed, randbuf, sizeof (randbuf), &random_data_RPS);
    };
  int32_t res;
  int er = random_r (&random_data_RPS, &res);
  if (er)
    FATAL ("failed to call random_r (%s)", strerror (er));
  return res;
}                               /* end randomi32_RPS */

int
main (int argc, char **argv)
{
  assert (argc > 0);
  progname_RPS = argv[0];
  pthread_setname_np (pthread_self (), "main-rpsjit");
  rl_initialize ();             /// initialize readline
  zlibv_RPS = zlibVersion ();
  jitctx_RPS = gcc_jit_context_acquire ();
  if (!jitctx_RPS)
    FATAL ("%s failed to create jitctx_RPS (%s)", progname_RPS,
           strerror (errno));
  snprintf (full_source_main_RPS, sizeof (full_source_main_RPS), "%s/%s",
            sourcedir_RPS, __FILE__);
  if (access (full_source_main_RPS, R_OK))
    FATAL ("%s failed to access full_source_main_RPS %s (%s)",
           progname_RPS, full_source_main_RPS, strerror (errno));
  backtrace_state_RPS =
    backtrace_create_state (full_source_main_RPS, /*THREADED: */ 1,
                            backtrace_error_RPS, NULL);
  // should define textual formats, a few global variables, what they
  // contain, how is the libgccjit transforming textual data to
  // code... Some global variables are pointers functions and they
  // could need a libgccjit computation
#warning TODO a lot of things
  gcc_jit_context_release (jitctx_RPS);
  printf ("%s ending successfully (git %s) source in %s\n",
          progname_RPS, shortgitid_RPS, full_source_main_RPS);
  return 0;
}                               /* end main */
