/****************************************************************
 * file gccjit-refpersys/main.c
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Description:
 *      This file is part of the Reflective Persistent System.
 *      Some gccjit variant to please indian programmers
 *      It is almost its main program.
 *
 * Author(s):
 *      Basile Starynkevitch, France   <basile@starynkevitch.net>
 *
 * past indian contributors
 *      Abhishek Chakravarti, India    <abhishek@taranjali.org>
 *      Nimesh Neema, India            <nimeshneema@gmail.com>
 *
 *      © Copyright 2019 - 2026 The Reflective Persistent System Team
 *      team@refpersys.org & http://refpersys.org/
 *
 * You can consider RefPerSys as either GPLv3+ or LGPLv3+ licensed (at
 * your choice)
 *
 * License: GPLv3+ (file COPYING-GPLv3)
 *    This software is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details or the Lesser
 *    General Public License.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ***/

#include "hdgjirps.h"

char full_source_main_HDGJIRPS[384];


thread_local struct random_data random_data_HDGJIRPS;
thread_local volatile atomic_flag random_inited_HDGJIRPS;



#ifndef SOURCEDIR
#error compilation command without SOURCEDIR
#endif

const char sourcedir_HDGJIRPS[] = SOURCEDIR;

const char main_HDGJIRPS_git[] = SHORTGITID;

static void backtrace_error_HDGJIRPS (void *data, const char *msg,
				      int errnum);
static void parse_program_option_HDGJIRPS (int argc, char **argv);
static void program_usage_HDGJIRPS (void);
extern void load_file_HDGJIRPS (const char *ldpath);

double
wallclock_real_time_HDGJIRPS (void)
{
  struct timespec ts = { 0, 0 };
  if (clock_gettime (CLOCK_REALTIME, &ts))
    return NAN;
  return 1.0 * ts.tv_sec + 1.0e-9 * ts.tv_nsec;
}				/* end wallclock_real_time_HDGJIRPS */

double
monotonic_real_time_HDGJIRPS (void)
{
  struct timespec ts = { 0, 0 };
  if (clock_gettime (CLOCK_MONOTONIC, &ts))
    return NAN;
  return 1.0 * ts.tv_sec + 1.0e-9 * ts.tv_nsec;
}				// end monotonic_real_time_HDGJIRPS


double
process_cpu_time_HDGJIRPS (void)
{
  struct timespec ts = { 0, 0 };
  if (clock_gettime (CLOCK_PROCESS_CPUTIME_ID, &ts))
    return NAN;
  return 1.0 * ts.tv_sec + 1.0e-9 * ts.tv_nsec;
}				// end process_cpu_time_HDGJIRPS


double
thread_cpu_time_HDGJIRPS (void)
{
  struct timespec ts = { 0, 0 };
  if (clock_gettime (CLOCK_THREAD_CPUTIME_ID, &ts))
    return NAN;
  return 1.0 * ts.tv_sec + 1.0e-9 * ts.tv_nsec;
}				// end thread_cpu_time_HDGJIRPS


void
backtrace_error_HDGJIRPS (void *data, const char *msg, int errnum)
{
  if (data)
    {
    };
  fprintf (stderr, "backtrace_error_HDGJIRPS: %s (%d:%s)\n", msg, errnum,
	   strerror (errnum));
  fflush (NULL);
}				/* end backtrace_error_HDGJIRPS */


void
emit_gplv3_notice_AT_HDGJIRPS (FILE *fout, const char *fil, int lin,
			       const char *fromfun, const char *path,
			       const char *linprefix, const char *linsuffix,
			       char *explain)
{
  assert (fout);
  assert (path);
#define EMIT_PRINTF(Fmt,...) do {               \
    if (linprefix)                              \
      fputs(linprefix,fout);                    \
  fprintf(fout,Fmt,##__VA_ARGS__);              \
  if (linsuffix)                                \
    fputs(linsuffix,fout);                      \
  fputc('\n', fout);                            \
} while(0)
  time_t nowtime = time (NULL);
  struct tm nowtm = { };
  localtime_r (&nowtime, &nowtm);
  EMIT_PRINTF ("SPDX-License-Identifier: GPL-3.0-or-later");
  EMIT_PRINTF ("GENERATED [GPLv3+] file %s / DO NOT EDIT", path);
  if (explain)
    EMIT_PRINTF ("! %s !", explain);
  EMIT_PRINTF ("! generating git %s !", shortgitid_HDGJIRPS);
  EMIT_PRINTF ("This %s file is generated by %s from %s:%d:%s",
	       path, progname_HDGJIRPS, fil, lin, fromfun);
  EMIT_PRINTF ("© Copyright 2023 - %d - RefPerSys team",
	       (nowtm.tm_year + 1900));
  EMIT_PRINTF ("License: GPLv3+ (file COPYING-GPLv3)");
  EMIT_PRINTF ("see refpersys.org & github.com/RefPerSys/gccjit-refpersys");
  EMIT_PRINTF ("Contact team@refpersys.org and/or ...");
  EMIT_PRINTF ("Basile STARYNKEVITCH <basile@starynkevitch.net>");
  EMIT_PRINTF ("92340 Bourg-la-Reine (or b-star-y.tech µentreprise)");
#undef EMIT_PRINTF
}				/* end emit_gplv3_copyright_notice_AT_HDGJIRPS */

#define EMIT_GPLV3_COPYRIGHT_HDGJIRPS(Fout,Path,Lpref,Lsuff,Explain) \
  emit_gplv3_notice_AT_HDGJIRPS(Fout,                                \
                           __FILE__,__LINE__,__FUNCTION__,      \
                           (LPref),(Lsuff),(Explain))

int32_t
randomi32_HDGJIRPS (void)
{
  if (__builtin_expect
      (!atomic_flag_test_and_set (&random_inited_HDGJIRPS), true))
    {
      static thread_local char randbuf[128];
      memset (&random_data_HDGJIRPS, 0, sizeof (random_data_HDGJIRPS));
      if (getrandom (&randbuf, sizeof (randbuf), 0) <
	  (long) sizeof (randbuf) / 2)
	HDGJIRPS_FATAL ("failed to initialize random (%s)", strerror (errno));
      unsigned seed = (unsigned) (time (NULL) + getpid ());
      initstate_r (seed, randbuf, sizeof (randbuf), &random_data_HDGJIRPS);
    };
  int32_t res = 0;
  do
    {
      int er = random_r (&random_data_HDGJIRPS, &res);
      if (er)
	HDGJIRPS_FATAL ("failed to call random_r (%s)", strerror (er));
    }
  while (res == 0);
  return res;
}				/* end randomi32_HDGJIRPS */

int64_t
randomi64_HDGJIRPS (void)
{
  int64_t x =
    ((unsigned long) randomi32_HDGJIRPS () << 32) | ((unsigned long)
						     randomi32_HDGJIRPS ());
  return x;
}

int verbose_HDGJIRPS;

enum longopt_HDGJIRPS_en
{
  noneopt__HDGJIRPS = 0,
  random_optHDGJIRPS = 1000,
  lastopt__HDGJIRPS
};

const struct option progopt_HDGJIRPS[] = {

  {.name = "verbose",.has_arg = no_argument,.flag = NULL,.val = 'V'},
  {.name = "version",.has_arg = no_argument,.flag = NULL,.val = 'v'},
  {.name = "help",.has_arg = no_argument,.flag = NULL,.val = 'H'},
  {.name = "load",.has_arg = required_argument,.flag = NULL,.val = 'l'},
  {.name = "random",.has_arg = no_argument,.flag = NULL,
   .val = (int) random_optHDGJIRPS},
  {.name = NULL,.has_arg = no_argument,.flag = NULL,.val = 0}
};				/* end progopt_HDGJIRPS */



void
program_usage_HDGJIRPS (void)
{
  printf ("%s usage:\n", progname_HDGJIRPS);
  printf ("\t -V | --verbose         # verbose flag\n");
  printf ("\t -v | --version         # version info\n");
  printf ("\t -H | --help            # this help\n");
  printf ("\t      --random          # prints a random id\n");
  printf ("\t -l | --load <topfile>  # load heap from TOPFILE\n");
  printf
    ("%s is GPLv3+ licensed, so WITHOUT WARRANTY;\n"
     " see www.gnu.org/licenses/gpl-3.0.html and refpersys.org\n"
     " and github.com/RefPerSys/ggccjit-refpersys\n", progname_HDGJIRPS);
  fflush (NULL);
}				/* end prog_usage_HDGJIRPS */

void
parse_program_option_HDGJIRPS (int argc, char **argv)
{
  //     extern char *optarg;
  //     extern int optind, opterr, optopt;
  int opt = -1;
  int ix = -1;
  do
    {
      opt = getopt_long (argc, argv, "VvHl:", progopt_HDGJIRPS, &ix);
      switch (opt)
	{
	case 0:
	  continue;
	case -1:
	  break;
	case 'V':		/* --verbose */
	  printf ("%s is verbose (pid %d on %s), GPLv3+ licensed\n",
		  progname_HDGJIRPS, (int) getpid (), hostname_HDGJIRPS);
	  verbose_HDGJIRPS = 1;
	  break;
	case 'v':		/* --version */
	  printf ("%s version gitid %s built on %s\n", progname_HDGJIRPS,
		  shortgitid_HDGJIRPS, __DATE__ "@" __TIME__);
	  printf ("\t C version %ld, compiler %s\n", __STDC_VERSION__,
		  __VERSION__);
	  printf ("\t libunistring version: %d.%d.%d\n",
		  _libunistring_version >> 16,
		  0xff & (_libunistring_version >> 8),
		  _libunistring_version & 0xff);
	  printf ("\t GNU libc version: %s [%s]\n", gnu_get_libc_version (),
		  gnu_get_libc_release ());
	  printf ("\t libgccjit version: %d.%d.%d\n",
		  gcc_jit_version_major (), gcc_jit_version_minor (),
		  gcc_jit_version_patchlevel ());
	  printf ("%s is GPLv3+ licensed, so WITHOUT WARRANTY;\n"
		  " see www.gnu.org/licenses/gpl-3.0.html\n",
		  progname_HDGJIRPS);
	  printf ("\t Its source code could be on %s\n",
		  "github.com/RefPerSys/gccjit-refpersys/");
	  break;
	case 'H':		/* --help */
	  program_usage_HDGJIRPS ();
	  break;
	case 'l':
	  if (loadpath_HDGJIRPS)
	    HDGJIRPS_FATAL ("cannot load more than once (%s & %s)",
			    loadpath_HDGJIRPS, optarg);
	  loadpath_HDGJIRPS = optarg;
	  break;
	case random_optHDGJIRPS:
	  printf ("%ld\n", (long) randomi64_HDGJIRPS ());
	  break;
	default:
	  break;
	};
    }
  while (opt >= 0);
}				/* end parse_program_option_HDGJIRPS */


void
load_file_HDGJIRPS (const char *ldpath)
{
  extern void load_state_HDGJIRPS (const char *path, const void *start,
				   const void *last);
  struct stat ldstat = { };
  int ldfd = open (ldpath, R_OK);
  if (ldfd < 0)
    HDGJIRPS_FATAL ("%s failed to open loaded file %s (%s)",	//
		    progname_HDGJIRPS, ldpath, strerror (errno));
  if (!jitctx_HDGJIRPS)
    HDGJIRPS_FATAL ("%s without jitctx_HDGJIRPS", progname_HDGJIRPS);
  if (fstat (ldfd, &ldstat))
    HDGJIRPS_FATAL ("%s failed to fstat loaded file %s (%s) fd#%d",	//
		    progname_HDGJIRPS, ldpath, strerror (errno), ldfd);
  size_t ldsize = ldstat.st_size;
  size_t pgsize = getpagesize ();
  size_t memsize = (ldsize % pgsize) ? (1 + (ldsize | (pgsize - 1))) : ldsize;
  size_t mmapsize = memsize;
  if (verbose_HDGJIRPS)
    {
      printf ("%s: [%s:%d] mmap mmapsize=%zd ldfd#%d ldsize=%zd ldpath:%s\n",
	      progname_HDGJIRPS, __FILE__, __LINE__ - 1, mmapsize, ldfd,
	      ldsize, ldpath);
      fflush (NULL);
    }
  const void *ldad = mmap (NULL, mmapsize, PROT_READ,
			   MAP_SHARED,	/* MAP_HUGETLB dont work here */
			   ldfd, 0);
  if (ldad == MAP_FAILED)
    HDGJIRPS_FATAL ("%s failed to mmap fd#%d (%zd Kbytes)"
		    " for loaded file %s (%s)",
		    progname_HDGJIRPS, ldfd, mmapsize >> 10, ldpath,
		    strerror (errno));
  const void *ldend = (const char *) ldad + mmapsize;
  if (ldsize % pgsize == 0)
    {
      const void *zad = mmap ((void *) ldend, pgsize, PROT_READ,
			      MAP_FIXED | MAP_PRIVATE | MAP_ANON,	/* MAP_HUGETLB dont work here */
			      -1, 0);
      if (zad != ldend)
	HDGJIRPS_FATAL ("%s failed to mmap zero page at %p"
			" for loaded file %s (%s)",
			progname_HDGJIRPS, ldend, ldpath, strerror (errno));
    };
  assert (*(const char *) ldend == (char) 0);
  if (verbose_HDGJIRPS)
    {
      printf ("%s mmaped loaded file %s (fd#%d) for %zd Kbytes @%p-%p\n",
	      progname_HDGJIRPS, ldpath, ldfd, mmapsize >> 10, ldad, ldend);
      fflush (NULL);
    };
  load_state_HDGJIRPS (ldpath, ldad, ldend);
}				/* end load_file_HDGJIRPS */

static void
getexec_HDGJIRPS (void)
{
  ssize_t s = readlink ("/proc/self/exe",
			executable_HDGJIRPS,
			sizeof (executable_HDGJIRPS) - 1);
  if (s < 0 || !executable_HDGJIRPS[0])
    HDGJIRPS_FATAL ("%s failed to readlink /proc/self/exe (%s)",
		    progname_HDGJIRPS, strerror (errno));
  if (access (executable_HDGJIRPS, R_OK | X_OK))
    HDGJIRPS_FATAL ("%s has bad executable %s (%s)",
		    progname_HDGJIRPS, executable_HDGJIRPS, strerror (errno));
}				/* end getexec_HDGJIRPS */

static void *progdlh_HOGJIRPS;

void *
full_program_dlhandle_HOGJIRPS (void)
{
  return progdlh_HOGJIRPS;
}				/* end full_program_dlhandle_HOGJIRPS */

int
main (int argc, char **argv)
{
  assert (argc > 0);
  progname_HDGJIRPS = argv[0];
  progdlh_HOGJIRPS = dlopen (NULL, RTLD_LAZY);
  pthread_setname_np (pthread_self (), "main-rpsjit");
  gethostname (hostname_HDGJIRPS, sizeof (hostname_HDGJIRPS));
  getexec_HDGJIRPS ();
  parse_program_option_HDGJIRPS (argc, argv);
  rl_initialize ();		/// initialize readline
  zlibv_HDGJIRPS = zlibVersion ();
  jitctx_HDGJIRPS = gcc_jit_context_acquire ();
  if (!jitctx_HDGJIRPS)
    HDGJIRPS_FATAL ("%s failed to create jitctx_HDGJIRPS (%s)",
		    progname_HDGJIRPS, strerror (errno));
  snprintf (full_source_main_HDGJIRPS, sizeof (full_source_main_HDGJIRPS),
	    "%s/%s", sourcedir_HDGJIRPS, __FILE__);
  if (access (full_source_main_HDGJIRPS, R_OK))
    HDGJIRPS_FATAL ("%s failed to access full_source_main_HDGJIRPS %s (%s)",
		    progname_HDGJIRPS, full_source_main_HDGJIRPS,
		    strerror (errno));
  backtrace_state_HDGJIRPS =
    backtrace_create_state ("/proc/self/exe", /*THREADED: */ 1,
			    backtrace_error_HDGJIRPS, NULL);
  if (loadpath_HDGJIRPS)
    load_file_HDGJIRPS (loadpath_HDGJIRPS);
  gcc_jit_context_release (jitctx_HDGJIRPS);
  if (verbose_HDGJIRPS)
    printf ("%s ending successfully (git %s) on %s (pid %d) source in %s\n",
	    progname_HDGJIRPS, shortgitid_HDGJIRPS, hostname_HDGJIRPS,
	    (int) getpid (), full_source_main_HDGJIRPS);
  return 0;
}				/* end main */
